### ISSUE TITLE
Améliorations SEO (meta title / description)

### ISSUE THREAD

**Issue by maximaLzdnb** [Augora/Augora#361]
## Description

Les balises title et meta description du projet ne semblent pas être intégrées correctement pour le référencement : https://i.imgur.com/rILqcNb.png ([vu ici](https://www.google.com/search?q=site%3Aaugora.fr&oq=site%3Aaugora.fr))
C'est également vrai pour les pages des députés et la FAQ.

On note aussi que certaines URLs ont un "| Augora" et d'autres "- Augora" en suffixe : je ne sais pas si c'est le googlebot qui est à la ramasse ou si vous avez fait un demi switch de convention seulement.

En arrivant sur le site, la balise title est mise à jour par contre : c'est géré en mode SPA ? Dans tous les cas je pense que des balises plus travaillées peuvent aider en terme de référencement, et ultimement pour le reach du projet.

## Proposition

Les balises title de l'ensemble du site (en mode SPA donc ?) me paraissent très bien. Pour les meta description, des suggestions mais à retravailler bien sûr :

- **Accueil** : "Vous voulez en savoir plus sur les députés de **l'Assemblée Nationale** ? Augora est un projet open source qui permet à chacun d'être mieux renseigné sur la **politique Française**." : en gras les mots clés que je juge important.
- **Page député** : "Informations générales et coordonnées de **{Prenom Nom}**, **{député}|{députée} {parti}** de la **{# circonscription}** de **{département}**."

_Exemple pour https://augora.fr/depute/yves-daniel : 
"Informations générales et coordonnées de Yves Daniel, député LREM de la 6ème circonscription de Loire-Atlantique."_

**Comment by goldenivan** [comment]
Bonjour,

Tout d'abord, merci pour la proposition ! 🎉 Nous avons bien vu cette dernière. Nous avons une tâche sur ce sujet. Cela a mis en lumière d'autres problèmes, que nous allons prendre en compte.

**Comment by KevinBacas** [comment]
Hello @maximaLzdnb, je viens de commencer à travailler sur cette partie.
On en a profité pour revoir un peu la façon dont on s'occupait du SEO et de la balise <head/> en général :)

Si jamais ça t'intéresse, tu peux suivre tout ça sur #375. Un petit lien devrait être présent dans un commentaire avec les nouvelles features de la pull request.
On a encore un peu de review à faire (car je suis pas le meilleur rédacteur du groupe 🤦) et un peu de bug fix et ça devrait pas tarder à voir le jour.

Merci encore pour tes retours.
